### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by valentinoguerra** [erluxman/pdf_flutter#4]
I've only tried on android, and only using the pdf from network.  In debug mode works properly but then when you build an apk, the app crashes instantly when is supposed to show the pdf. To reproduce the error you just have to create a new project and add the PDF. network widget provided by the package, then build an apk.
For what I tried, this package is just what I need for my app and works great, except for this 'little' issue. I hope you can solve it.

**Comment by erluxman** [comment]
Acknowledged, Will debug it in the weekend. I hope that won't be too late..

**Comment by Hantuch1860** [comment]
I'm experiencing the same issue with pdf from asset. Thank you for this package. Good luck solving the issue.

**Comment by valentinoguerra** [comment]
> Acknowledged, Will debug it in the weekend. I hope that won't be too late..

Any update of the issue?

**Comment by erluxman** [comment]
I tried to do the same but my app doesn't crash.. It says socket expectation. Can you provide me your error logs?

**Comment by erluxman** [comment]
Fixed by https://github.com/erluxman/pdf_flutter/commit/3398a9fd88da9389e649c2efa7a1f20277d66d2d

Asset seems to work fine for me.. 

Please let me know @Hantuch1860 .

**Comment by valentinoguerra** [comment]
I've tried with the new version but somehow is still not working for me, same as before. 

I can´t provide the log errors because it only happens with the apk build, I tried in profile and release mode but works perfectly on those. 

If you have any idea of how can I provide you the log errors just tell me and I'll do it. Thanks

**Comment by erluxman** [comment]
What do you mean by build then? Which mode are you building your apk with? Can you provide me the steps (with commands/menu clicks)?

**Comment by valentinoguerra** [comment]
Simply run the command 'flutter build apk' in terminal. Then if you send the apk file to a real android phone and open the file to install the app, there is where the pdf doesn't shows.

**Comment by erluxman** [comment]
Ok will try to find some time to fix this...

**Comment by mirandaink01** [comment]
I have the same problem

**Comment by erluxman** [comment]
Now I also experienced the same issue, Any idea how to see the flutter logs in release APK?

**Comment by MobileMon** [comment]
I'm having the same problem. When running from Android studio it works fine, but when building an apk and installing it crashes

You can see the logs on your device by plugging your phone into your computer and running 'adb logcat' from the terminal

The exceptions I get are:

Pending exception java.lang.ClassNotFoundException: com.shockwave.pdfium.util.Size

 at com.shockwave.pdfium.b.a com.shockwave.pdfium.PdfiumCore.nativeGetPageSizeByIndex(long, int, int)

at com.shockwave.pdfium.b.a com.shockwave.pdfium.PdfiumCore.b(com.shockwave.pdfium.a, int)

This only happens on Android, not an iOS

**Comment by MobileMon** [comment]
I solved it!

Its related to this issue: https://stackoverflow.com/questions/59045522/everything-works-fine-when-install-from-android-studio-and-same-results-when-i-i

Here are the steps to fix:

1. Add proguard-rules.pro file if its not already there 
<img width="228" alt="Screen Shot 2020-08-31 at 7 53 46 PM" src="https://user-images.githubusercontent.com/2768159/91779534-e288fd00-ebc3-11ea-9c6f-d3e3a9d0922c.png">

2. Inside of the proguard-rules.pro file put this:
-keep class com.shockwave.**
-keepclassmembers class com.shockwave.** { *; }

in app/build.gradle add this:

<img width="228" alt="Screen Shot 2020-08-31 at 7 53 46 PM" src="https://user-images.githubusercontent.com/2768159/91779577-09dfca00-ebc4-11ea-8fca-5dc6ebd36eb1.png">

shrinkResources true
minifyEnabled true
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

**Comment by erluxman** [comment]
Oh my God, you are the Savior 😊

Can I bother you to make a PR so that I don't miss any stuff? A little bit busy sorry 😐

**Comment by erluxman** [comment]
Plus you taught me a pretty simple no brainer that my brain didn't realize. running `adb logcat` how stupid of me 😝

**Comment by maltub9** [comment]
I have the same problem I tried the above steps using proguard etc... and the app crush when I load a pdf.

**Comment by erluxman** [comment]
added

**Comment by AtaKarakas** [comment]
Although I follow these steps, I continue to have the same problem
